import { expect, it } from "vitest";
import { buildData } from "./data";
import { buildSchema } from "./schema";
import { model } from "./test/model";

it("buildData", () => {
  const schema = buildSchema(model);
  const data = buildData(schema);

  expect(data).toMatchInlineSnapshot(`
    [
      {
        "count": 3,
        "directives": {},
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "name",
        ],
        "index": 0,
        "name": "Class",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Class-id-1",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Class-id-2",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Class-id-3",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-3",
            },
          ],
        ],
      },
      {
        "count": 3,
        "directives": {},
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "name",
        ],
        "index": 1,
        "name": "Club",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-3",
            },
          ],
        ],
      },
      {
        "count": 9,
        "directives": {},
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "age",
          "userId",
        ],
        "index": 2,
        "name": "Profile",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-1",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-2",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-3",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-3",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-4",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-4",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-5",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-5",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-6",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-6",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-7",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-7",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-8",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-8",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Profile-id-9",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "age",
              "nullable": true,
              "scalar": true,
              "type": "Int",
              "value": 0,
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
                "unique": {},
              },
              "list": false,
              "name": "userId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "User-id-9",
            },
          ],
        ],
      },
      {
        "count": 9,
        "directives": {},
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "classId",
          "name",
        ],
        "index": 3,
        "name": "User",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-1",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-1",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-2",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-2",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-3",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-3",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-3",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-4",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-1",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-4",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-5",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-2",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-5",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-6",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-3",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-6",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-7",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-1",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-7",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-8",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-2",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-8",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-9",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Class",
                },
              },
              "list": false,
              "name": "classId",
              "nullable": true,
              "scalar": true,
              "type": "String",
              "value": "Class-id-3",
            },
            {
              "directives": {},
              "list": false,
              "name": "name",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "name-9",
            },
          ],
        ],
      },
      {
        "count": 27,
        "directives": {
          "join": {},
        },
        "fields": [
          "id",
          "createdAt",
          "updatedAt",
          "clubId",
          "userId",
        ],
        "index": 4,
        "name": "ClubToUser",
        "values": [
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-1",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-2",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-3",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-3",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-4",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-4",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-5",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-5",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-6",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-6",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-7",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-7",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-8",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-8",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-9",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-9",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-10",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-11",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-12",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-3",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-13",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-4",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-14",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-5",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-15",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-6",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-16",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-7",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-17",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-8",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-18",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-9",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-19",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-1",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-20",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-2",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-21",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-3",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-22",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-4",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-23",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-5",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-24",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-6",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-25",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-1",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-7",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-26",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-2",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-8",
            },
          ],
          [
            {
              "directives": {},
              "list": false,
              "name": "id",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "ClubToUser-id-27",
            },
            {
              "directives": {},
              "list": false,
              "name": "createdAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {},
              "list": false,
              "name": "updatedAt",
              "nullable": false,
              "scalar": true,
              "type": "Date",
              "value": 1970-01-01T00:00:00.000Z,
            },
            {
              "directives": {
                "ref": {
                  "name": "Club",
                },
              },
              "list": false,
              "name": "clubId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "Club-id-3",
            },
            {
              "directives": {
                "ref": {
                  "name": "User",
                },
              },
              "list": false,
              "name": "userId",
              "nullable": false,
              "scalar": true,
              "type": "String",
              "value": "User-id-9",
            },
          ],
        ],
      },
    ]
  `);
});
